name: Create weekly progress report Issue

on:
  schedule:
    - cron: '17 * * * *'

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get today's date
        id: date
        run: |
          echo "::set-output name=today::$(date --date="next Sunday" "+%Y-%m-%d")"

      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: Progress report ${{ steps.date.outputs.today }}
          body: |
            What did you do this week? 

          labels: |
            question
