name: Create weekly progress report Issue

on:
  schedule:
    - cron: '5 * * * *' # At 09:00 on Monday

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get today's date
        id: date
        run: |
          echo "::set-output name=today::$(date --date="next Sunday" "+%Y-%m-%d")"

      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: Progress report ${{ steps.date.outputs.today }}
          body: |
            ## This week's TODO

            - [ ] Have a meeting with UX team
            - [ ] Check the dashboard

          labels: |
            question
